// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: pkg/proto/receiver.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StreamingServiceClient is the client API for StreamingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamingServiceClient interface {
	Streaming(ctx context.Context, opts ...grpc.CallOption) (StreamingService_StreamingClient, error)
}

type streamingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamingServiceClient(cc grpc.ClientConnInterface) StreamingServiceClient {
	return &streamingServiceClient{cc}
}

func (c *streamingServiceClient) Streaming(ctx context.Context, opts ...grpc.CallOption) (StreamingService_StreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &StreamingService_ServiceDesc.Streams[0], "/service.StreamingService/Streaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamingServiceStreamingClient{stream}
	return x, nil
}

type StreamingService_StreamingClient interface {
	Send(*Message) error
	CloseAndRecv() (*Resp, error)
	grpc.ClientStream
}

type streamingServiceStreamingClient struct {
	grpc.ClientStream
}

func (x *streamingServiceStreamingClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *streamingServiceStreamingClient) CloseAndRecv() (*Resp, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Resp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StreamingServiceServer is the server API for StreamingService service.
// All implementations must embed UnimplementedStreamingServiceServer
// for forward compatibility
type StreamingServiceServer interface {
	Streaming(StreamingService_StreamingServer) error
	mustEmbedUnimplementedStreamingServiceServer()
}

// UnimplementedStreamingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStreamingServiceServer struct {
}

func (UnimplementedStreamingServiceServer) Streaming(StreamingService_StreamingServer) error {
	return status.Errorf(codes.Unimplemented, "method Streaming not implemented")
}
func (UnimplementedStreamingServiceServer) mustEmbedUnimplementedStreamingServiceServer() {}

// UnsafeStreamingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamingServiceServer will
// result in compilation errors.
type UnsafeStreamingServiceServer interface {
	mustEmbedUnimplementedStreamingServiceServer()
}

func RegisterStreamingServiceServer(s grpc.ServiceRegistrar, srv StreamingServiceServer) {
	s.RegisterService(&StreamingService_ServiceDesc, srv)
}

func _StreamingService_Streaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamingServiceServer).Streaming(&streamingServiceStreamingServer{stream})
}

type StreamingService_StreamingServer interface {
	SendAndClose(*Resp) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type streamingServiceStreamingServer struct {
	grpc.ServerStream
}

func (x *streamingServiceStreamingServer) SendAndClose(m *Resp) error {
	return x.ServerStream.SendMsg(m)
}

func (x *streamingServiceStreamingServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StreamingService_ServiceDesc is the grpc.ServiceDesc for StreamingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.StreamingService",
	HandlerType: (*StreamingServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Streaming",
			Handler:       _StreamingService_Streaming_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/proto/receiver.proto",
}
